### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by itsjustyryr** [feelfreelinux/cspot#144]
Can it play music in the background?

**Comment by itsjustyryr** [comment]
That's what I've done, waiting for an answer! Fingers crossed, and thanks!

**Comment by Ryan-Romig** [comment]
it looks like to me  Cspot-vita uses the Cspot library as a submodule to work on PS vita platform instead of ESP32 or CLI. not the whole Cspot project. 

similar to adding a PS-Vita folder to the cspot/targets if that makes sense

**Comment by itsjustyryr** [comment]
> it looks like to me  Cspot-vita uses the Cspot library as a submodule to work on PS vita platform instead of ESP32 or CLI. not the whole Cspot project. 
> 
> 
> 
> similar to adding a PS-Vita folder to the cspot/targets if that makes sense

I also noticed that! I was curious if one of them has the ability to play music in the background, even if you play in Adrenaline(emulator for PSP/PS1 games)

**Comment by Ryan-Romig** [comment]
> > it looks like to me  Cspot-vita uses the Cspot library as a submodule to work on PS vita platform instead of ESP32 or CLI. not the whole Cspot project.
> > similar to adding a PS-Vita folder to the cspot/targets if that makes sense
> 
> I also noticed that! I was curious if one of them has the ability to play music in the background, even if you play in Adrenaline(emulator for PSP/PS1 games)

what do you mean in the background? do you mean on the PS-Vita platform?
If you are running an emulator on a PC, you could run CSpot CLI and the emulator both.

**Comment by itsjustyryr** [comment]
> > > it looks like to me  Cspot-vita uses the Cspot library as a submodule to work on PS vita platform instead of ESP32 or CLI. not the whole Cspot project.
> 
> > > similar to adding a PS-Vita folder to the cspot/targets if that makes sense
> 
> > 
> 
> > I also noticed that! I was curious if one of them has the ability to play music in the background, even if you play in Adrenaline(emulator for PSP/PS1 games)
> 
> 
> 
> what do you mean in the background? do you mean on the PS-Vita platform?
> 
> If you are running an emulator on a PC, you could run CSpot CLI and the emulator both. 
Sorry. On the PS-Vita platform, yes. Can it be used with LowMemMode so the app would run in the background?
