### ISSUE TITLE
Zeroconf auth support + auth token persistence

### ISSUE THREAD

**Issue by feelfreelinux** [feelfreelinux/cspot#2]
Add support to authentication via zeroconf/mdns. 
- Launch a server on random port handling GET `getInfo` and `addUser`
- Solve challenge based on addUser data
- Resulting token can then be used with Session

we should also persist auth token blobs in targets instead of relogging every single time

**Comment by feelfreelinux** [comment]
Working implementation in https://github.com/feelfreelinux/cspot/commit/66910743c46f19a440819bc62903c11b26dc75cd

**Comment by feelfreelinux** [comment]
Added MbedTLS implementation in: https://github.com/feelfreelinux/cspot/commit/20a0f6a8478db1ba3a8058c55742b1533f8302fd

**Comment by feelfreelinux** [comment]
Will merge once confirmed working on esp-idf platform

**Comment by feelfreelinux** [comment]
Closed in https://github.com/feelfreelinux/cspot/pull/26

**Comment by alufers** [comment]
![seeal](https://media1.tenor.com/images/4495febcf4164476d2f8ae35740a7597/tenor.gif?itemid=3375882)
