### ISSUE TITLE
Add dynamic apresolve

### ISSUE THREAD

**Issue by feelfreelinux** [feelfreelinux/cspot#3]
right now spotify ap address is hardcoded in `PlainConnection.cpp`.
- Query "http://apresolve.spotify.com" to receive ap address
- Connect to this address in `PlainConnection.cpp`.

**Comment by feelfreelinux** [comment]
Fixed in https://github.com/feelfreelinux/cspot/commit/5aed5e0b9d335ce29c368efd5af26d0b9de6b315

**Comment by sle118** [comment]
Nicely done! This will be very helpfu!
