### ISSUE TITLE
Build failed on Windows (missing 'protos/AnyRefImpl.cpp')

### ISSUE THREAD

**Issue by adamhun94** [feelfreelinux/cspot#46]
Hi,
I just received my ESP32-A1S audio board for this project, and I'm trying to build a binary for it on Windows.
I installed the SDK and set up VS Code as well. When I'm trying to the build the project (from targets/esp32 folder) I get the following error:
```
CMake Error at ../../cspot/CMakeLists.txt:40 (add_library):
  Cannot find source file:

    protos/AnyRefImpl.cpp
```

I pulled the submodules and installed the python libs (pip3 install protobuf grpcio-tools)
What am I doing wrong?

Thanks!

**Comment by adamhun94** [comment]
I checked out https://github.com/feelfreelinux/cspot/commit/0613aaadcaa9ef3da9cfb3f8258e66db5de583de since it's marked as a success build (sorry for missing that).

I was able to build it and flash it, so now I'm testing it. Thanks for your hard work!

**Comment by feelfreelinux** [comment]
Hi, thanks for reporting this. We switched to a custom protobuf implementation a while ago so that's probably why the process might be quite wonky. I'll look into it soon :)

**Comment by philippe44** [comment]
I was trying to give another try to integrate into squeezelite-esp32 but I had the same issue. I'll wait till you have the time to figure out what's wrong with Windows build as this is my main system

**Comment by feelfreelinux** [comment]
> I checked out [0613aaa](https://github.com/feelfreelinux/cspot/commit/0613aaadcaa9ef3da9cfb3f8258e66db5de583de) since it's marked as a success build (sorry for missing that).
> 
> I was able to build it and flash it, so now I'm testing it. Thanks for your hard work!

Actually, docs don't state that but you need to have golang installed and in your path for the new version to work. Let me know if you encounter any other issues on Windows

**Comment by adamhun94** [comment]
I just figured it out (and feel a little bit dumb), but I missed **generate_protos.sh** which generates the missing files.
I wrote this batch script for Windows if you don't have git bash:
```
cd ../cpp-reflection
go build -o protoc-gen-cpprefl .
cd ..
mkdir protos
protoc --plugin=protoc-gen-cpprefl=cpp-reflection/protoc-gen-cpprefl --cpprefl_out protos/ protocol/*.proto --proto_path protocol/
```
Place it inside the cmake folder.

I also had to download the [protobuf binary](https://github.com/protocolbuffers/protobuf/releases/latest) and add to PATH

Now I have a successful build from the latest commit.
_(haven't tried it flashing though, I'm not currently at home)_

FYI @philippe44

**Comment by feelfreelinux** [comment]
> I just figured it out (and feel a little bit dumb), but I missed **generate_protos.sh** which generates the missing files.
> I wrote this batch script for Windows if you don't have git bash:
> 
> ```
> cd ../cpp-reflection
> go build -o protoc-gen-cpprefl .
> cd ..
> mkdir protos
> protoc --plugin=protoc-gen-cpprefl=cpp-reflection/protoc-gen-cpprefl --cpprefl_out protos/ protocol/*.proto --proto_path protocol/
> ```
> 
> Place it inside the cmake folder.
> 
> I also had to download the [protobuf binary](https://github.com/protocolbuffers/protobuf/releases/latest) and add to PATH
> 
> Now I have a successful build from the latest commit.
> _(haven't tried it flashing though, I'm not currently at home)_
> 
> FYI @philippe44

`generate_protos.sh` is an extremely hacky version of doing it and I really need to fix it up.  Right not it doesn't even log the errors properly.

**Comment by feelfreelinux** [comment]
Protobuf decoding was reworked in newest master, now works through cmake. Thanks a lot @kuba2k2 :)
