### ISSUE TITLE
Does PCM5102 also work with MAX98357

### ISSUE THREAD

**Issue by don41382** [feelfreelinux/cspot#53]
Hi Filip,

Thanks for the awesome project! Does the PCM5102 sink also works with the MAX98357? Maybe somebody already checked this out.

Felix

**Comment by feelfreelinux** [comment]
Hi! From what I've seen the I2S format required for it is pretty similar, so it should work without any issues. Let me know if it works fine, we can always just add support for MAX98357 separately :)

**Comment by don41382** [comment]
I'll try and let you know. My biggest challenge is still to get it deployed via platformio. I am coming more from the Arduino world and not so familiar with working directly with esp-idf. This is off-topic, but do you have some guidance to deploy it to a esp32?

**Comment by don41382** [comment]
Finally got my wrover TTGO T7 working and I can confirm, that the `PCM5102AudioSink` works also with the `MAX98357A`.

I just had to change the pins according to my connections:

```
    i2s_pin_config_t pin_config = {
        .bck_io_num = 26,
        .ws_io_num = 25,
        .data_out_num = 22,
        .data_in_num = -1 //Not used
    };
```
