### ISSUE TITLE
No sound on ESP32-A1S board on the latest commit (d63c98a)

### ISSUE THREAD

**Issue by adamhun94** [feelfreelinux/cspot#62]
I just compiled a new fw based on the latest commit (https://github.com/feelfreelinux/cspot/commit/d63c98aa4e50a55316ff06d0994e6c0db5ff477f) for the ES32-A1S audio board.  I defined sink as AC101 in main.cpp:
`#define SINK        AC101`

I can successfully connect to the player, but there is no output on the earphones jack. Previously I had to adjust the volume (on my phone) after boot to have sound output, but now I can't make it happen.

**Comment by michal4132** [comment]
I incorrectly used preprocessor macros in this commit. Try applying changes from this PR #63.

**Comment by adamhun94** [comment]
Thanks! Now it's working again!

**Comment by feelfreelinux** [comment]
Fixed on master
