### ISSUE TITLE
fails on reserving pool in internal RAM when compiles in optimization mode Debug (-Og)

### ISSUE THREAD

**Issue by ehabulhaq** [feelfreelinux/cspot#67]
Hi, 

I used the project and ran it on a LyraTD-dspg board and it ran perfect. 

I am trying to incorporate ESP-MDF into the project. I am forced to compile the project in Optimization Level Debug for ESP-MDF. It fails on finding some inline functions of ESP-MDF if I compile in (-Os).

The project compiles fine but when I run it it gets stuck on reserving pool in internal memory  and the whole code resets. I am attaching the output:

entry 0x40080710
I (31) boot: ESP-IDF v4.2-dirty 2nd stage bootloader
I (31) boot: compile time 13:56:26
I (31) boot: chip revision: 3
I (34) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (41) qio_mode: Enabling default flash chip QIO
I (46) boot.esp32: SPI Speed      : 80MHz
I (51) boot.esp32: SPI Mode       : QIO
I (56) boot.esp32: SPI Flash Size : 4MB
I (60) boot: Enabling RNG early entropy source...
I (66) boot: Partition Table:
I (69) boot: ## Label            Usage          Type ST Offset   Length
I (76) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (84) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (91) boot:  2 factory          factory app      00 00 00010000 00200000
I (99) boot:  3 storage          Unknown data     01 82 00210000 00100000
I (106) boot: End of partition table
I (111) boot_comm: chip revision: 3, min. application chip revision: 0
I (118) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x4737c (291708) map
I (223) esp_image: segment 1: paddr=0x000573a4 vaddr=0x3ffbdb60 size=0x041e0 ( 16864) load
I (230) esp_image: segment 2: paddr=0x0005b58c vaddr=0x40080000 size=0x00404 (  1028) load
0x40080000: _WindowOverflow4 at C:/Users/haqeh/esp/components/freertos/xtensa/xtensa_vectors.S:1730

I (231) esp_image: segment 3: paddr=0x0005b998 vaddr=0x40080404 size=0x04680 ( 18048) load
I (246) esp_image: segment 4: paddr=0x00060020 vaddr=0x400d0020 size=0x1008ac (1050796) map
0x400d0020: _stext at ??:?

I (596) esp_image: segment 5: paddr=0x001608d4 vaddr=0x40084a84 size=0x156b0 ( 87728) load
0x40084a84: esp_timer_impl_set_alarm at C:/Users/haqeh/esp/components/esp_timer/src/esp_timer_impl_lac.c:164

I (645) boot: Loaded app from partition at offset 0x10000
I (645) boot: Disabling RNG early entropy source...
I (646) psram: This chip is ESP32-D0WD
I (650) spiram: Found 64MBit SPI RAM device
I (655) spiram: SPI RAM mode: flash 80m sram 80m
I (660) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (667) cpu_start: Pro cpu up.
I (671) cpu_start: Application information:
I (676) cpu_start: Project name:     cspot-esp32
I (681) cpu_start: App version:      d63c98a-dirty
I (687) cpu_start: Compile time:     Jun 28 2021 13:56:08
I (693) cpu_start: ELF file SHA256:  f960b42dc76765d6...
I (699) cpu_start: ESP-IDF:          v4.2-dirty
I (704) cpu_start: Starting app cpu, entry point is 0x40081f24
0x40081f24: call_start_cpu1 at C:/Users/haqeh/esp/components/esp32/cpu_start.c:287

I (695) cpu_start: App cpu up.
I (1207) spiram: SPI SRAM memory test OK
I (1208) heap_init: Initializing. RAM available for dynamic allocation:
I (1208) heap_init: At 3FFAE6E0 len 0000F480 (61 KiB): DRAM
I (1214) heap_init: At 3FFC7240 len 00018DC0 (99 KiB): DRAM
I (1220) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1227) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1233) heap_init: At 4009A134 len 00005ECC (23 KiB): IRAM
I (1239) cpu_start: Pro cpu start user code
I (1244) spiram: Adding pool of 4081K of external SPI memory to heap allocator
I (0) spi_flash: detected chip: generic
I (0) spi_flash: flash io: qio
I (0) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
**I (0) spiram: Reserving pool of 64K of internal memory for DMA/internal allocations**

abort() was called at PC 0x40085092 on core 0
0x40085092: lock_acquire_generic at C:/Users/haqeh/esp/components/newlib/locks.c:142

Backtrace:0x4008ed6a:0x3ffb4860 0x4008f459:0x3ffb4880 0x40094596:0x3ffb48a0 0x40085092:0x3ffb4910 0x400851c9:0x3ffb4940 0x401b673d:0x3ffb4960 0x401ad8bf:0x3ffb4c20 0x401ad77a:0x3ffb4c70 0x4009363b:0x3ffb4ca0 0x400d36f7:0x3ffb4cc0 0x400d3749:0x3ffb4d00 0x400d4ffb:0x3ffb4d40 0x400d45c4:0x3ffb4d70 0x4008f461:0x3ffb4da0
0x4008ed6a: panic_abort at C:/Users/haqeh/esp/components/esp_system/panic.c:330

0x4008f459: esp_system_abort at C:/Users/haqeh/esp/components/esp_system/system_api.c:106

0x40094596: abort at C:/Users/haqeh/esp/components/newlib/abort.c:46

0x40085092: lock_acquire_generic at C:/Users/haqeh/esp/components/newlib/locks.c:142

0x400851c9: _lock_acquire_recursive at C:/Users/haqeh/esp/components/newlib/locks.c:170

0x401b673d: _vfiprintf_r at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/stdio/vfprintf.c:853 (discriminator 2)

0x401ad8bf: fiprintf at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/stdio/fiprintf.c:48

0x401ad77a: __assert_func at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/stdlib/assert.c:58 (discriminator 8)

0x4009363b: get_next_block at C:/Users/haqeh/esp/components/heap/multi_heap.c:131
 (inlined by) multi_heap_get_info_impl at C:/Users/haqeh/esp/components/heap/multi_heap.c:790

0x400d36f7: heap_caps_get_info at C:/Users/haqeh/esp/components/heap/heap_caps.c:453

0x400d3749: heap_caps_get_largest_free_block at C:/Users/haqeh/esp/components/heap/heap_caps.c:441

0x400d4ffb: esp_spiram_reserve_dma_pool at C:/Users/haqeh/esp/components/esp32/spiram.c:199

0x400d45c4: main_task at C:/Users/haqeh/esp/components/esp32/cpu_start.c:558

0x4008f461: vPortTaskWrapper at C:/Users/haqeh/esp/components/freertos/xtensa/port.c:143

It is compiled as Optimization level Debug (-Og)

**Comment by feelfreelinux** [comment]
Resolved in newest master, all allocation is now done on PSRAM
