### ISSUE TITLE
ESP32 crashes and restarts with given album

### ISSUE THREAD

**Issue by adamhun94** [feelfreelinux/cspot#69]
If you play one of the songs from this album, you get esp32 to restart: https://open.spotify.com/album/5bJntfSwnGsPWH0xJg4mu4

I did some debugging and saw the following in SpotifyTrack.cpp: 
```
trackInfo.restriction.size() == 22
canPlayTrack(trackInfo.restriction) == false
```
so it goes to while cycle, but then:
`trackInfo.alternative.size() == 0`
so it crashes.

I don't know much about restrictions, but if I check for trackInfo.alternative.size > 0, actually the song started to play although canPlayTrack returned false.

**Comment by feelfreelinux** [comment]
Unable to reproduce on newer master, possibly because of being in a different country. Will keep a closer eye on the restrictions support
